### PR TITLE
Add map styles, option to hide infowindows and fix bugs

### PR DESCRIPTION
**Pull request by renekorss**
Since I didn't found any update `.sql` files, this query is needed to update from older versions:

    ALTER TABLE `#__phocamaps_map` ADD `mapstyles` MEDIUMTEXT NOT NULL AFTER `kmlfile`;

Please add it where it's supposed to be. Also made PR to plugin to support styled maps.

### CODE REVIEW

**Comment by PhocaCz** [comment]
Hi, thank you for the changes, two questions:

1) why it is necessary to change the database structure, why not store 
mapsstyles in Options of Phoca Maps. Should it be related to map only or 
can it be related to whole component/plugin? Mostly database change can 
be problematic when updating component - on some servers

2) are you able to change the "file changed" here on github, there are 
88 changes but mostly these are not real changes (empty row added, empty 
row removed). Because of the count of such confusing changes the file is 
not good readable (the real changes are not readable :-( )

Thank you, Jan

Dne 29. 6. 2016 v 11:37 Rene Korss napsal(a):

**Comment by renekorss** [comment]
1. It should be map specific.
2. Yes, I can do that. It was my automatic editorconfig. But I'll do it tomorrow.

**Comment by renekorss** [comment]
I have now managed to change files an revert to your spacing.

**Comment by PhocaCz** [comment]
Thank you very much, implemented in version 3.0.4

**Pull request merged**
